version: '3.9'

services:
  mongo-server:
    image: mongo:latest
    container_name: mongo-server
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

  mongo-client:
    image: mongo-express:latest
    container_name: mongo-client
    restart: always
    depends_on:
      - mongo-server
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-server
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8081:8081"
    networks:
      - my_network

  oracle-server:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-server
    restart: always
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=1234
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - my_network

volumes:
  mongodb_data:
  oracle_data:

networks:
  my_network:
