---CREAR EL USUARIO PARA LA PRUEBA TECNICA
CREATE USER C##DISTELSA IDENTIFIED BY 1234;
--Permisos
GRANT CONNECT, RESOURCE TO C##DISTELSA;
GRANT SELECT ANY TABLE, INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE TO C##DISTELSA;
--Espacio de registros
ALTER USER C##DISTELSA QUOTA UNLIMITED ON USERS;

---CREAR LAS TABLAS
CREATE TABLE STUDENTS (
    ID_STUDENT NUMBER(10) GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    DPI VARCHAR(13) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE COURSES (
    ID_COURSE NUMBER(10) PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREDITS NUMBER(2) NOT NULL
);

CREATE TABLE ASSIGNMENTS (
    ID_ASSIGNMENT NUMBER(10) PRIMARY KEY,
    ID_STUDENT NUMBER(10) NOT NULL,
    ID_COURSE NUMBER(10) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    ASSIGNMENT_DATE DATE,
    CONSTRAINT FK_STUDENT FOREIGN KEY (ID_STUDENT) REFERENCES STUDENTS(ID_STUDENT),
    CONSTRAINT FK_COURSE FOREIGN KEY (ID_COURSE) REFERENCES COURSES(ID_COURSE)
);


-- AGREGAR RESTRICCIÓN DE ESTADO VÁLIDO EN ASIGNACIONES
ALTER TABLE ASSIGNMENTS
ADD CONSTRAINT CK_STATUS_ASSIGNMENT CHECK (STATUS IN ('PENDIENTE', 'APROBADO', 'RECHAZADO', 'ANULADO'));


SELECT * FROM STUDENTS
SELECT * FROM COURSES
SELECT * FROM ASSIGNMENTS

--DROP TABLE STUDENTS
--DROP TABLE COURSES
--DROP TABLE ASSIGNMENTS